### ISSUE TITLE
How to convert the trained model to keras model?

### ISSUE THREAD

**Issue by chunyang-zhang** [npahucki/RealTimePoseEsitmationDancingGame#1]
Thanks for your great work! I had converted the video data into a model by "train_model.py", but I don't know how to use "kerasify" to convert the trained model into something that can be used in C++.  Could you give me some advice?

**Comment by npahucki** [comment]
Not sure if you still have a question here seeing that you closed the issue, but there is an example of how to do that in https://github.com/npahucki/RealTimePoseEsitmationDancingGame/blob/master/python/train_model.py#L57

**Comment by chunyang-zhang** [comment]
Thank you very much for your advice, I had known how to use "train_model.py", so I close the issue.
